server:
  port: ${PORT:8030}
  contextPath: /payment-ms
  context-path: /payment-ms  # spring-boot-admin 
    
# give the application a name
spring:
  application:
    name: payment-ms
# custom attribute for the actuator info endpoint
info:
  app:
    name: payment-ms

# configure eureka client. Enamble/disable with @EnableEurekaClient App 
eureka:
  instance:
    registryFetchIntervalSeconds: 30
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    hostname: localhost
    preferIpAddress: true
    statusPageUrlPath: ${server.context-path}/info
    healthCheckUrlPath: ${server.context-path}/health
  client:
    enabled: true
    serviceUrl:
      #defaultZone: http://user:password@localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/ 

 
    
logging.level:
    org:
        springframework:
            ui: warn
            aop: warn
            jdbc: warn
            data: warn
            context: warn
            test: warn
            beans: warn
            orm: warn
            core: warn
            boot: warn
            web: warn
        hibernate: error
        apache: warn
        jboss.logging: warn
    com.netflix.discovery: warn
    com.ea: debug
