server:
  port: ${PORT:8761} # Indicate the default PORT where this service will be started

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # telling the server not to register himself in the service
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
      
    
logging.level:
    org:
        springframework:
            ui: warn
            aop: warn
            jdbc: warn
            data: warn
            context: warn
            test: warn
            beans: warn
            orm: warn
            core: warn
            boot: warn
            web: warn
        hibernate: warn
        hibernate.SQL: warn
        apache: warn
        jboss.logging: warn
