server:
  port: ${PORT:8098}
  
  

# give the application a name
spring:
  application:
    name: course-ms
# custom attribute for the actuator info endpoint
info:
  app:
    name: course-ms
    
# disable actuator security for endpoints 
management:
  security:
    enabled: false

# configure eureka client
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
    

    
    
stub:
    payment-ms: true
    
    
logging.level:
    org:
        springframework:
            ui: warn
            aop: warn
            jdbc: warn
            data: warn
            context: warn
            test: warn
            beans: warn
            orm: warn
            core: warn
            boot: warn
            web: warn
        hibernate: warn
        hibernate.SQL: warn
        apache: warn
        jboss.logging: warn
    com.ea: debug
