#server:
#    port: 8081
#
#management:
#    security:
#        enabled: false
#    port: 9001
    
    
stub:
    payment-ms: true
    
    
logging.level:
    org:
        springframework:
            ui: warn
            aop: warn
            jdbc: warn
            data: warn
            context: warn
            test: warn
            beans: warn
            orm: warn
            core: warn
            boot: warn
            web: warn
        hibernate: warn
        hibernate.SQL: warn
        apache: warn
        jboss.logging: warn
