server:
  port: ${PORT:8020}
  contextPath: /student-ms
  context-path: /student-ms # spring-boot-admin 

# give the application a name
spring:
  application:
    name: student-ms
# custom attribute for the actuator info endpoint
info:
  app:
    name: student-ms

# configure eureka client. 
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    statusPageUrlPath: ${server.context-path}/info
    healthCheckUrlPath: ${server.context-path}/health
  client:
    enabled: true #on/off eureka
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
    

#rest:
#  payment-ms:
#    url: http://localhost:8030/payment-ms
    
stub:
    payment-ms: false
    
    
logging.level:
    org:
        springframework:
            ui: warn
            aop: warn
            jdbc: warn
            data: warn
            context: warn
            test: warn
            beans: warn
            orm: warn
            core: warn
            boot: warn
            web: warn
        hibernate: error
        apache: warn
        jboss.logging: warn
    com.ea: debug
    com.netflix: info
