server:
  port: ${PORT:8020}
  contextPath: /student-ms
  context-path: /student-ms # spring-boot-admin 


# configure eureka client. Enamble/disable with @EnableEurekaClient App 
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
    
spring:
  application:
    name: student-ms
info:
  app:
    name: student-ms


    
    
stub:
    payment-ms: false
    
    
logging.level:
    org:
        springframework:
            ui: warn
            aop: warn
            jdbc: warn
            data: warn
            context: warn
            test: warn
            beans: warn
            orm: warn
            core: warn
            boot: warn
            web: warn
        hibernate: error
        apache: warn
        jboss.logging: warn
    com.ea: debug
    com.netflix: info
